### ISSUE TITLE
Converted 2.2 Project Doesn't Appear

### ISSUE THREAD

**Issue by Cons-Cat** [sanbox-irl/gm-code-vsc#2]
One 2.2 project, converted to 2.3.0.529, doesn't appear in the GM Code tree. Other 2.2 projects converted to 2.3 do seem to work perfectly. I have converted this project to 2.3 multiple times, and it consistently does not appear in the GM Code tree, so there must be something unique to this project that causes issues.

It is a fairly large project, so perhaps this issue is related to the its size?

![image](https://user-images.githubusercontent.com/1811218/94760086-94f0e300-036f-11eb-95c7-f1a4447e394c.png)

I can send the 2.2 and/or the 2.3 folders if that would help.

**Comment by sanbox-irl** [comment]
if you DM me on discord the 2.3 project, I'll take a tool. unfortunately, I probably need the entire thing to diagnose. in the next version, I'm working on better error messages so users can better understand when things don't work

**Comment by sanbox-irl** [comment]
closing for release of 0.2
